### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by ak-matsu** [ak-matsu/furima-34248#15]

**Comment by snkw-works** [comment]
@ak-matsu さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **商品購入にて、配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であるよう修正しましょう**
「都道府県」の入力がなくても、購入ができてしまいます。

- [ ] **issueにIDとパスワードを記載しましょう**
Basic認証のIDとパスワードの記載がない状態です。今回はID「admin」、パスワード「2222」でアプリが表示されたため、挙動確認させていただいておりますが、issueを編集し、記載をお願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@ak-matsu さん、お待たせいたしました。ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/123537162-02983700-d769-11eb-806c-1cdd0d002b02.png)
